apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: fastapi-app
  namespace: flux-system
spec:
  interval: 1m
  path: "./apps/fastapi-app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: elk-stack
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/elk"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: k6-tests
  namespace: flux-system
spec:
  interval: 1m
  path: "./infrastructure/k6"
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-repo

